# Generated by Django 2.2.5 on 2020-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerdetails',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payerdetails',
            name='note',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payerdetails',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
