# Generated by Django 2.2.5 on 2020-09-30 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payerdetails',
            name='note',
        ),
    ]
