# Generated by Django 2.2.5 on 2020-10-02 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0002_remove_payerdetails_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payerdetails',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='payerdetails',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.AddField(
            model_name='payerdetails',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 2, 17, 42, 29, 2491, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payerdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payerdetails',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='payerdetails',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
