# Generated by Django 2.2.5 on 2020-10-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0003_auto_20201002_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payerdetails',
            old_name='account',
            new_name='is_owner',
        ),
    ]
