# Generated by Django 2.2.5 on 2020-10-03 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentsapp', '0004_auto_20201002_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payerdetails',
            options={},
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='payerdetails',
            name='username',
        ),
        migrations.AddField(
            model_name='payerdetails',
            name='payer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
