# Generated by Django 2.2.5 on 2020-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0007_auto_20201004_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payerdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
