# Generated by Django 2.2.5 on 2020-09-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_paid',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='orders',
            name='tx_ref',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
