# Generated by Django 2.2.5 on 2020-09-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20200929_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
