# Generated by Django 2.2.5 on 2020-10-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_orders_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
    ]
