# Generated by Django 2.2.5 on 2020-10-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_remove_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tx_ref',
        ),
    ]
