# Generated by Django 3.0.3 on 2020-09-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_auto_20200915_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
