# Generated by Django 3.0.3 on 2020-09-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0006_auto_20200916_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
