# Generated by Django 2.2.5 on 2020-09-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
