# Generated by Django 2.2.5 on 2020-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0010_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
