# Generated by Django 2.2.5 on 2020-09-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0001_initial'),
        ('cartapp', '0011_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentsapp.PayerDetails'),
        ),
    ]
